### ISSUE TITLE
Outdated sphinx version?

### ISSUE THREAD

**Issue by rumpelsepp** [syncthing/docs#1]
Hey, which version do you use to generate the docs? In my machine it looks slightly different from the homepage (mind the nav):

local
![screenshot from 2015-05-29 10-13-15](https://cloud.githubusercontent.com/assets/1961699/7878888/64b301f0-05eb-11e5-836c-e793b229f02e.png)

docs.syncthing.net
![screenshot from 2015-05-29 10-13-24](https://cloud.githubusercontent.com/assets/1961699/7878893/69263fa4-05eb-11e5-9cd0-b0bf04cd0bdd.png)

seems that I am on the most recent sphinx release:

```
$ sphinx-build --version
Sphinx (sphinx-build) 1.3.1
```

**Comment by calmh** [comment]
1.3.1 there as well. At least it's broken on your side, not the public one. :)

**Comment by rumpelsepp** [comment]
```
$ pacman -Q python-sphinx_rtd_theme
python-sphinx_rtd_theme 0.1.6-3
```

Indeed. Sorry for the noise, and thanks for the pointer! :)
