### ISSUE TITLE
use case for symlink which is not resolved with current experimental feature:  syncing the configuration files of applications 

### ISSUE THREAD

**Issue by andrewufrank** [syncthing/docs#121]
i have accounts on several computers (who has not?) and i would like to have them behave as much as possible the same - including installation of programs and configurations. my ideal situation would be that in a synced folder i would collect links (soft links) to the config files and if i change one on one computer  the change is found on any other. the selection of which file to synchronize must be on a file by file choice as not all config files are suitable. i think examples for suitable files are e.g. nautlus uca.xml, where additional user actions are defined; it is a great nuisance to propagate such changes ...

the current feature - as much as i understand from the documentation - is taking the content of a file which is linked and puts it on the target. my use case requires that, if the target contains a link as well, the content is written to the linked file, not replacing the link. 

i understand that this has some possible dangerous implications, but it seems reasonably checked, as there must be links in both synced directories, but i do not see them as more difficult or dangerous as the ones emerging with ignoring files for sync. (which leads to non-empty directories, which cannot automatically be deleted and produce "out of date".

**Comment by calmh** [comment]
This is the issue tracker for the documentation, not the program itself. That's said, the experimental follow sum links feature was never merged as it was considered more trouble (danger) than the value delivered; this suggestion may not be more dangerous but certainly more niche. As such it seems unlikely to be put on the roadmap, but you are certainly welcome to file the request in the syncthing issue tracker.
