### ISSUE TITLE
"-no-restart" is not fully documented

### ISSUE THREAD

**Issue by ProactiveServices** [syncthing/docs#123]
There doesn't seem to be mention of the fact that -no-restart suppresses the monitor instance. Does it have other behaviour that needs to be documented? Should it really be "-no-restart"?

**Comment by calmh** [comment]
The option historically takes its name from the fact that when set syncthing does not restart when told to restart, nor when it crashes, it just exits. As an effect of suppressing the monitor process. It is the equivalent of the STNORESTART environment variable. We both for ... you guessed it, historical reasons. :)

**Comment by rumpelsepp** [comment]
see also #94

**Comment by lkwg82** [comment]
So is this historical reason still valid or is this just an usefull opportunity to remove some *historical waste*? ;)

**Comment by lkwg82** [comment]
bump

**Comment by calmh** [comment]
My guess is it can "never" be changed since there are scripts out there that depend on both.

**Comment by lkwg82** [comment]
What are these scripts? What for? Can we give some warning over a long time "deprecated switch, instead use this ..."?

**Comment by calmh** [comment]
Probably all over the place. I don't see much value in deprecating it, it's literally a half line of code to support the env var in addition to the command line switch.

**Comment by lkwg82** [comment]
So we should keep and document it.

**Comment by xor-gate** [comment]
GUI wrappers which manage the syncthing process by itself instead of service-managers (systemd, launchd et al) should be able to control the startup of syncthing. As @calmh said we should not deprecate this, but I agree to @lkwg82 we should keep and document it.

**Comment by imsodin** [comment]
Fixed by #278
