### ISSUE TITLE
Share ID not read-only

### ISSUE THREAD

**Issue by mightyCelu** [syncthing/docs#134]
When accepting a directory from another device it is possible to change the ID.
The added directory will not synchronize, without any error message. Additionaly the "Add folder" dialog will be triggered over and over again.

For the user this is counterintuitive. From a technichal standpoint I also don't see the need for having the user-chosable ID to be the same among all devices (without knowing the syncthing protocol). It would be convenient if I could name a share "Images" on my smartphone and "Smartphone Images" on my Computer.

**Comment by AudriusButkevicius** [comment]
Not sure why you are opening this in the documentation repo. Regardless, this has now been changed in the master repo, and due to be released with 0.13. You will have a randomly generated ID, and a label, where the label can be different per device.

**Comment by mightyCelu** [comment]
Alright, I accidentaly used the wrong repository, glad to see it is resolved.
