### ISSUE TITLE
update get started guide

### ISSUE THREAD

**Issue by lkwg82** [syncthing/docs#139]
PR syncthing/syncthing#2668 introduced folder labels
PR syncthing/syncthing#2830 moved advanced fields into collapsed block

This needs to update the getting started guide. (wording and screenshots)

**Comment by tomasz1986** [comment]
This also seems to have been fixed by #554 (see https://github.com/syncthing/docs/issues/255#issuecomment-779584246).

**Comment by AudriusButkevicius** [comment]
Agree.
