### ISSUE TITLE
Document expansion

### ISSUE THREAD

**Issue by rumpelsepp** [syncthing/docs#15]
A reminder for:
https://github.com/syncthing/syncthing/issues/1924#issuecomment-110708578

These questions appear regularly, so let's add a note about that in syncthing(1).

**Comment by calmh** [comment]
For the record, syncthing here works exactly the same as `rm`, `touch`, `mkdir` or basically any other shell command. Not that it would hurt to spell it out.

**Comment by rumpelsepp** [comment]
Yeah, but maybe we should mention that service managers (usually) do not support expansion. I think that's the source of the confusion…
