### ISSUE TITLE
Mention and deprecate user-contrib OS X application

### ISSUE THREAD

**Issue by xor-gate** [syncthing/docs#188]
Hi all,

As I started a native OS X application in Objective-C it would be nice so other people can find it:
https://github.com/syncthing/docs/blob/master/users/contrib.rst#os-x

Should add:
https://github.com/xor-gate/syncthing-macosx

The following is deprecated and I will not maintain this further:
https://github.com/xor-gate/syncthing-mac

Kind regards,
Jerry

**Comment by canton7** [comment]
Edit the docs and submit a PR :)
