### ISSUE TITLE
Unknown version of the protocol

### ISSUE THREAD

**Issue by sargelavoie** [syncthing/docs#191]
I have syncthing running on a Windows 10 PC (64 bit), and a Raspberry Pi 2 NFS mounted to a NAS. I recently had a problem with the NAS, so I changed successfully one of my RAID1 disk. Yesterday, I have update both syncthing, and since then, the windows node throw this error message:

"Connecting to ABCDEFG-HIJKLMN-OPQRSTU-VWXYZA-BCDEFGH-IJKLMNO-PQRSTUV-WXYZABC (123.456.789.1:0000): the remote device speaks an unknown (newer?) version of the protocol"

As a consequence, my raspberry pi sees my PC connected and synchronized, but my PC says that my raspberry pi is disconnected.

Any idea?

**Comment by calmh** [comment]
What are the versions involved?

**Comment by AudriusButkevicius** [comment]
So first of all this ticket does not belong here (it's a documentstion repo).
Secondly, use the forum for questions like this, as you probably downloaded incompatible versions.
