### ISSUE TITLE
No need to scan an unshared folder

### ISSUE THREAD

**Issue by tomtom** [syncthing/docs#196]
syncthing duly scans all folders (at least once on startup). It also scans folders that aren't shared with any known node.

I'd propose to check if it's ok for syncthing not to scan unshared folders.

**Comment by AudriusButkevicius** [comment]
So first of all, this is the documentation repo, so this does not belong here.
Secondly I think its beneficial to scan the folder no matter what, so that when you do share it its ready to go. I even think this is used as a feature in some cases.

**Comment by AudriusButkevicius** [comment]
Some cases being block reuse,  prescanning a folder before sharing and prescanning on a more powerful device.

**Comment by tomtom** [comment]
Oops, wrong repo. Sorry.
