### ISSUE TITLE
Move "Event API" to "REST API" section

### ISSUE THREAD

**Issue by xduugu** [syncthing/docs#217]
It just happened the second time to me that I looked for the events endpoint, but couldn't find it in the "[REST API](https://docs.syncthing.net/dev/rest.html)" section.

Is there a reason why the [events endpoint](https://docs.syncthing.net/dev/events.html) is documented separately from the other REST endpoints? Could it be moved to the "REST API" section, or if not could we a least get a link from the "REST API" page to the "Event API" section?

**Comment by AudriusButkevicius** [comment]
It's because it's quite verbose, and has a different way of accessing it.

**Comment by calmh** [comment]
There could certainly be a link from the corresponding thing under "rest api". But it's important enough to warrant it's own section with documentation of the different events.

**Comment by xduugu** [comment]
@AudriusButkevicius
With differently accessed, you are referring to its blocking nature?

@calmh 
I didn't meant to remove anything from the events documentation. The suggestion was only to rename the file to rest/events-get.rst, since at least for me, it's yet another REST endpoint. But actually, I don't care where the documentation is stored and the link is placed.

Does the link to the events fit into the "Misc Services Endpoints" section or is there a better place?
