### ISSUE TITLE
Intro to GUI out of date

### ISSUE THREAD

**Issue by JohnVeness** [syncthing/docs#255]
The screenshots on intro/gui.html need updating, as there are now headings for Folders, This Device, Remote Devices.

Also, on small screens, the list of Folders appears above the list of Devices, rather than on the left/right, which will need reflecting in the text somehow.

**Comment by JohnVeness** [comment]
Similarly screenshots/text in intro/getting-started.html

**Comment by tomasz1986** [comment]
I think that this has been fixed by https://github.com/syncthing/docs/pull/554. Is this correct?

**Comment by AudriusButkevicius** [comment]
Think so.
