### ISSUE TITLE
Exit Code 2 is documented wrong

### ISSUE THREAD

**Issue by Nutomic** [syncthing/docs#265]
The docs say exit code 2 means "Upgrade not available". But [according to Audrius](https://github.com/syncthing/syncthing-android/issues/759#issuecomment-268741112) it is also "the exit code returned by the runtime on panic".

**Comment by calmh** [comment]
Yeah, it's both.

**Comment by Nutomic** [comment]
The thing is, I didnt treat this exit code as an error in the Android app, which lead to that issue. So the documentation should say that exit code 2 can also mean a crash. And even in a crash, the exit code should never be 0, 3 or 4, right?

**Comment by calmh** [comment]
You'll only ever get exit code 2 in the meaning of "upgrade not available" when running `syncthing -upgrade` specifically. I can't really guarantee what the exit code is or isn't in a crash as at that point someone else (the Go runtime, or the OS) has taken over. I'd be surprised if it was zero, though. For the other codes, does it really matter? Syncthing exited with something that was not the intention to stay shutdown forever, so the action to take is restart it?

**Comment by Nutomic** [comment]
So how can I check for shutdown, restart or crash in the Android wrapper?
https://github.com/syncthing/syncthing-android/blob/master/src/main/java/com/nutomic/syncthingandroid/service/SyncthingRunnable.java#L152

**Comment by calmh** [comment]
Shutdown is zero. Anything else is a restart or a crash so you restart it. If you want to be more specific, three is an intentional restart and everything else is a crash and thus unintentional restart.

**Comment by Nutomic** [comment]
I dont want to restart every time, because shutdown is also handled via exit codes. And errors should be reported, so they dont cause an infinite loop. So how about this:
0 -> shutdown
137 -> shutdown (sigkill)
3 -> restart
else -> error

**Comment by calmh** [comment]
Sure, if you prefer. The way our monitor process does it is that it restarts on nonzero exit. If there are four restarts in 15 seconds or so it concludes there is a problem and gives up.

**Comment by Catfriend1** [comment]
Hi,
I'm currently investigating a ticket where the user got exit code 2 unexpectedly. Does that mean it's an upgrade problem or panic in recent syncthing versions? The main.go code says "upgradeNotFound" but upgrades are always off on Android.

**Comment by AudriusButkevicius** [comment]
Check the logs

**Comment by Catfriend1** [comment]
It got lost in crash and it's not my phone, so how?

**Comment by AudriusButkevicius** [comment]
Idk. 2 means upgrade, if it happened in some other case you'd need to get the logs.

**Comment by Catfriend1** [comment]
Okay, maybe the user can provide logs or info if he did try to turn on the non existing upgrade feature in the app. Afaik the web ui doesn't allow turning it on due to compiler switches used during build.

**Comment by AudriusButkevicius** [comment]
You can't switch it on once it was disabled at compile time.
