### ISSUE TITLE
FAQ: sync between different Syncting folders

### ISSUE THREAD

**Issue by novoid** [syncthing/docs#268]
Hi!

I'd like to have a question and its answer added to the FAQ:

When I do have two distinct Syncthing-managed folders on two hosts, how does Syncthing handle moving files between them?

Example: Android and notebook are syncing the `DCIM` folder (the camera directory) and an `ARCHIVE` folder. Now I move all `DCIM` photographs to the `ARCHIVE` folder. Is this operation recognized as "moving known items from one folder to another" even though they are from different Syncthing folders (done instantly) or does this result in deleting all photographs in one Syncthing folder and newly transferring all photographs between the `ARCHIVE` instances (lasts looong)?

Thanks

**Comment by AudriusButkevicius** [comment]
So I am happy to answer your questions if you are willing to create the commits with the FAQ entries
