### ISSUE TITLE
Logging not working

### ISSUE THREAD

**Issue by DrStrangepork** [syncthing/docs#279]
OSX, running v0.14.19 with the following command: `/usr/local/opt/syncthing/bin/syncthing -no-browser -no-restart -logflags=7 -verbose -logfile=/var/log/syncthing.log`

No log file is created, no matter what settings I use for `logfile` or `logflags`. Running the command from a shell shows the expected logging to stdout with the VERBOSE logging (when specified). It just never writes to the logfile. I have run this on multiple machines running El Capitan and Sierra with same results.

**Comment by AudriusButkevicius** [comment]
This is the documentation repo, so it does not belong here, but you I can repro that, so feel free to reopen in github.com/syncthing/syncthing

**Comment by calmh** [comment]
I think it's even documented somewhere here that `-logfile` is incompatible with `-no-restart`, as `-no-restart` disabled the monitor process and it's the monitor process that implements `-logfile`.

**Comment by DrStrangepork** [comment]
Oh, well that could certainly be the cause of my issue. Sounds to me like if any OS-level process management is used to control syncthing, which should require `-no-restart`, would therefore eliminate the option to log syncthing. That seems suboptimal.

**Comment by calmh** [comment]
Agreed. Lets take the discussion in the other ticket, I responded here before seeing it.

https://github.com/syncthing/syncthing/issues/3912
