### ISSUE TITLE
The Linux part from "Starting Syncthing Automatically" is incorrect or outdated 

### ISSUE THREAD

**Issue by manuti** [syncthing/docs#311]
In the docs related to Linux [https://docs.syncthing.net/users/autostart.html?highlight=boot#linux](https://docs.syncthing.net/users/autostart.html?highlight=boot#linux) I think the step 2 in both *How to set up a system service* and *How to set up a user service* are incorrect or contain mistakes.

**Comment by AudriusButkevicius** [comment]
Docs are maintained by the community, so feel free to file a pull request fixing then.

**Comment by manuti** [comment]
OK I try to know how do the start on boot and then change the doc. 
Thanks.

**Comment by imsodin** [comment]
This is definitely an issue, so we should keep this open until it is actually fixed.

**Comment by manuti** [comment]
OK, I don't want to bother. Sorry for closing suddenly.

**Comment by rumpelsepp** [comment]
@manuti  Could you explain what you mean by "are incorrect or contain mistakes".

**Comment by rumpelsepp** [comment]
We could add a sentence that maybe the service is already there, depending on how the user has installed syncthing (e.g. via apt-get or manually).

**Comment by imsodin** [comment]
@rumpelsepp The path 

``Syncthing/etc/system/syncthing@.service``

in step 2 isn't correct. If you installed from source, you need to copy from ``./etc/linux-systemd/system`` in the source directory. Also if you installed via apt you don't need to copy anything as you mentioned.

On an extended note: In my opinion that page is too much, in the same sense as discussed in #261: This tries to document another project. In my opinion we should only mention that/where/how we provide the systemd service files, anything that is Syncthing specific about them or the setup and maybe a link to the relevant documentation/a good tutorial.

**Comment by rumpelsepp** [comment]
> On an extended note: In my opinion that page is too much, in the same sense as discussed in #261: This tries to document another project. In my opinion we should only mention that/where/how we provide the systemd service files, anything that is Syncthing specific about them or the setup and maybe a link to the relevant documentation/a good tutorial.

I agree, BUT we received a lot of bug reports and support questions because people did not know what is the difference between these. Also, they tried to start syncthing as root using a user service and so on. This paragraph helped reducing these questions, so I would like to keep them there; maybe we could simplify it. But we should keep it.

**Comment by acolomb** [comment]
> We could add a sentence that maybe the service is already there, depending on how the user has installed syncthing (e.g. via apt-get or manually).

I believe this is fixed.  There's nothing immediately actionable in this issue, so let's close it and wait for Someone(TM) to propose a better text.
