### ISSUE TITLE
Docs say systemd user units only start when logged in, but this isn't entirely correct

### ISSUE THREAD

**Issue by argv-minus-one** [syncthing/docs#319]
[This documentation section](https://docs.syncthing.net/users/autostart.html#using-systemd) claims that, if Syncthing is to be started as a systemd user service (that is, a `.service` file under `~/.config/systemd/user`), it will only start when the user is logged in.

This is indeed the default behavior, but there is another option here. If the administrator does `loginctl enable-linger {username}`, then that user's services are started when the machine boots, much like system services do.

The documentation should mention this option.

**Comment by AudriusButkevicius** [comment]
Feel free to file a pull request. Docs are editable straight from github.

**Comment by calmh** [comment]
I would rather the pull request go in the other direction and remove the errant info. Documenting systemd behavior seems like a fool's errand.

**Comment by AudriusButkevicius** [comment]
Fair play.

**Comment by canton7** [comment]
Or link to the systemd docs?

**Comment by imsodin** [comment]
I think it is very valid to have a quick explanation of the use case for user and system services. Saying that user services are started at login may not be correct in all cases, but being correct in the default case is good enough.
