### ISSUE TITLE
Documentation missing for file versioning

### ISSUE THREAD

**Issue by ssg** [syncthing/docs#321]
File versioning document explains different types of versioning strategies but has no pointers about how to enable it in the configuration XML (the configuration document points to the overview document only). That's a significant problem since versioning settings are not shown in the GUI.

**Comment by calmh** [comment]
Versioning is configured in the GUI, edit the folder and expand "advanced" at the bottom.

**Comment by ssg** [comment]
Oh I completely missed it, thanks!
