### ISSUE TITLE
Document behaviour of `-reset-database` 

### ISSUE THREAD

**Issue by HaleTom** [syncthing/docs#340]
Migrated from https://github.com/syncthing/syncthing/issues/4334

The only documentation in the [wiki](https://docs.syncthing.net/users/syncthing.html?highlight=#cmdoption-reset-database) on `-reset-database` is:

> Reset the database, forcing a full rescan and resync.

[This forum post](https://forum.syncthing.net/t/recreate-synced-folders-after-data-loss/10423/5?u=ataraxy) shows that `.stfolders` are created.

This has implications for unmounted disks so a caveat is probably in order.

[POST /rest/system/reset](https://docs.syncthing.net/rest/system-reset-post.html) may be affected also.

**Comment by AudriusButkevicius** [comment]
Given someone has spent time answering your questions, I'd be nice if you could update the docs in return.

**Comment by HaleTom** [comment]
Ok, I've worked out how edit the wiki pages in GitHub...

I'm wondering about the exact consequences of creating a `.stfolder` on an unmounted mountpoint.

I'm guessing it's not good:

1. Initially syncing data to an unexpected location (the unmounted mountpoint, possibly filling it)
2. Possible reversions to previous versions of files when the correct disk is later inserted and rescanned.

Is that an accurate summation?

How about adding the about the following text under `-reset-database`:

> Reset the database, forcing a full rescan and resync. **Caution**: This will create `.stfolder` folders in each sync location if they do not exist. Ensure that sync folders which are mountpoints are indeed mounted to prevent syncing of inconsistent versions.

**Comment by imsodin** [comment]
That should be right.
The text requires the reader to know what the consequences of creating ".stfolder" are. I would describe  the actual consequences: syncing to the unmounted mountpoint. I think this is it, any further complications are just consequences of that, which is a mistake in the first place.

**Comment by HaleTom** [comment]
Thanks imsodin, good point. 

I'm wondering if documenting this is the best long term strategy after all:

[Document or fix potentially dangerous side effect of `-reset database`?](https://forum.syncthing.net/t/document-or-fix-potentially-dangerous-side-effect-of-reset-database/10475)

**Comment by AudriusButkevicius** [comment]
This wouldn't delete data, as it would not be aware of data being there in the first place (db removed). Though if it gets mounted back, you might get reversions to old versions.

**Comment by HaleTom** [comment]
I had trouble viewing the rendered output.  http://rst.ninjs.org/ didn't help much.

How would I do that in future?
