### ISSUE TITLE
development issue for custom feature

### ISSUE THREAD

**Issue by dipenpatel235** [syncthing/docs#356]
hello.
i have created development setup and for that i am sending my device id over URL
so i have write that code in cmd/syncthing/main.go file.
then compile it.
and before my code i have  print static text for test bit not print on console .

so not getting idea what is wrong with compile.
i have doubt my code that part is not  executing or not compiled in binary.

so any developer can help me ?

Thanks

**Comment by AudriusButkevicius** [comment]
Please don't raise random issues in random repos, support is handled on the forum.
