### ISSUE TITLE
Wrong description for STUN options

### ISSUE THREAD

**Issue by acolomb** [syncthing/docs#357]
I was looking for an explanation what the `<stunServer>` option should be set to when I don't want to use any (only IPv6 external connectivity). The documentation on the corresponding options (`<stunKeepaliveSeconds>` as well) just contains some unrelated copy-and-paste residue:

[blob/master/users/config.rst](https://github.com/syncthing/docs/blob/master/users/config.rst#options-element)

**Comment by imsodin** [comment]
Yes indeed, that copy&paste residue slipped in in #355, thanks for pointing it out. To disable KCP use defaultListenAddress as explained [in this forum discussion](https://forum.syncthing.net/t/resolved-external-address-new-in-v0-14-40/10933/8?u=imsodin).

**Comment by acolomb** [comment]
Hm. I didn't realize that STUN is ONLY used for KCP. Same confusion as in the thread you mentioned, it seemed to me that it has to do with IPv4 NAT traversal.

So for IPv6, does STUN even provide any benefits? I don't want to disable KCP, just any protocol component that will try to use / advertise a non-working IPv4 DS-Lite address.

**Comment by AudriusButkevicius** [comment]
KCP is dual stack, yet it's purposes is to circumvent NATs.

**Comment by calmh** [comment]
STUN doesn't understand anything v6 related, far as I know. KCP offers you no advantage if you can get TCP established.
