### ISSUE TITLE
Request for Control Characters in .stignore 

### ISSUE THREAD

**Issue by HamishMacEwan** [syncthing/docs#373]
I was surprised they weren't there already, but would it be possible to ignore file names with say, a line-feed in them?  e.g. \n

**Comment by AudriusButkevicius** [comment]
Most of filesystems do not support filenames with control characters.

**Comment by HamishMacEwan** [comment]
Sounds like an excellent argument for being able to ignore them from filesystems that do.  Thank you.

**Comment by AudriusButkevicius** [comment]
You can always use ? which matches any character.

**Comment by HamishMacEwan** [comment]
If I knew in advance where in the name the \n (actually in the use case there are five of them) occurred, that would be helpful advice.

**Comment by calmh** [comment]
You might want to file a feature request on Syncthing. This is the documentation repo.

**Comment by HamishMacEwan** [comment]
Thank you for your helpful and useful suggestion.
