### ISSUE TITLE
Add stcli tool to the docs

### ISSUE THREAD

**Issue by xor-gate** [syncthing/docs#399]
As discussed in https://github.com/syncthing/syncthing/pull/5049#issuecomment-402864287. We should create a page for the stcli tool and keep it up-to-date. I'm creating this issue so we won't forget it.

**Comment by acolomb** [comment]
I believe this can be closed.  The `stcli` command got refactored into `syncthing cli` and for the latter we have an approximate description in https://docs.syncthing.net/users/syncthing.html.
