### ISSUE TITLE
Document the relaying functionality

### ISSUE THREAD

**Issue by calmh** [syncthing/docs#40]
- How it works in principle
- The config settings that are available
- How it looks in the GUI in the various stages

**Comment by AudriusButkevicius** [comment]
Also, update discovery format changes, device address format changes.

**Comment by AudriusButkevicius** [comment]
I guess only the last part is now relevant?

**Comment by calmh** [comment]
Yes. I guess references to the listeners thing wouldn't kill us either, but yes.
