### ISSUE TITLE
Syncing devices in vlans

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [syncthing/docs#400]
Hello,

My home router sets up two vlans with ip ranges in 192.168.1.1 and 10.0.0.1. I have a PC and a mobile devices that are in different vlan. 
Any advice on how to make syncthing work? At the moment, the devices can see each other only from time to time. And the sync gets stuck at 5% and it's slow near to no connection.

**Comment by AudriusButkevicius** [comment]
This is the documentation repo. Support is handled on the forum, yet I am sure there are plenty of existing threads that answer your question.
