### ISSUE TITLE
Event API issues

### ISSUE THREAD

**Issue by mjyu51** [syncthing/docs#404]
LocalChangeDetected and RemoteChangeDetected events were not documented correctly. It should be in /rest/events/disk, not /rest/events

**Comment by calmh** [comment]
They are available in the standard event point when passed in the “events” parameter. The disk endpoint is essentially deprecated.

**Comment by mjyu51** [comment]
I have tested /rest/events but never received these two events. However /rest/events/disk did return LocalChangeDetected and RemoteChangeDetected. 
Is there anything missing/special I should follow?

**Comment by AudriusButkevicius** [comment]
I think its not depreceted. I believe we split it out in order not to flood the main event pipe and not have important events roll off?

**Comment by canton7** [comment]
Yeah, that's my recollection as well.

**Comment by mjyu51** [comment]
I will test all the events and report back. I believe I didn't receive the DownloadProgress in the /rest/events (main event pipe) as well.

**Comment by AudriusButkevicius** [comment]
I am sure it's there as progress happens, as the UI would have issues showing download progress.

**Comment by AudriusButkevicius** [comment]
I guess its deprecates in a sense that you can now subscribe to an arbitary set of events, so it should use that instead.

**Comment by canton7** [comment]
True, but there's backwards compatibility to bear in mind

**Comment by AudriusButkevicius** [comment]
Are there any consumers of that? I doubt it.

**Comment by canton7** [comment]
I consume /rest/events, and I don't specify a filter.

**Comment by mjyu51** [comment]
I do consume all events, processing all of them.

**Comment by mjyu51** [comment]
DownloadProgress event: 
Document says returned information:
            "file1": {
                "Total": 800,
                "Pulling": 2,
                "CopiedFromOrigin": 0,
                "Reused": 633,
                "CopiedFromElsewhere": 0,
                "Pulled": 38,
                "BytesTotal": 104792064,
                "BytesDone": 87883776
            },

Test shows that the first char should be lower case:
            "file1": {
                "total": 800,
                "pulling": 2,
                "copiedFromOrigin": 0,
                "reused": 633,
                "copiedFromElsewhere": 0,
                "pulled": 38,
                "bytesTotal": 104792064,
                "bytesDone": 87883776
            },

**Comment by AudriusButkevicius** [comment]
Sure, feel free to fix it.

**Comment by imsodin** [comment]
Actually I am confused. The code says `/rest/events` without the event parameter gives all events except local and remote changes:  
endpoints: https://github.com/syncthing/syncthing/blob/master/cmd/syncthing/gui.go#L271  
event masks: https://github.com/syncthing/syncthing/blob/master/cmd/syncthing/gui.go#L56

But the documentation describing this behaviour was removed more or less recently by @calmh:  
https://github.com/syncthing/docs/commit/a13b3d5aaee4dbcadd525315f1d8e5239306522c#diff-73e41d6d6289cae6ed0dfe0452cabdef  
https://github.com/syncthing/docs/commit/a13b3d5aaee4dbcadd525315f1d8e5239306522c#diff-2ca6013a93b289f0272fd269dc9059f8  
https://github.com/syncthing/docs/commit/a13b3d5aaee4dbcadd525315f1d8e5239306522c#diff-c065c00f029e765682329281dc6b12b2

What is the intention here?

**Comment by calmh** [comment]
I don't recall thinking anything specific at that time. But I feel that the `.../disk` endpoint is deprecated, because it was created to serve just the change events before it was possible to specify event types in the subscription. The equivalent today would be `/rest/events?events=LocalChangeDetected,RemoteChangeDetected`. We should probably document what the default set of events is, maybe, as it is not *all* events. And the `.../disk` endpoint should go away, or be an alias (permanent redirect?) to the above.

**Comment by mjyu51** [comment]
I will try /rest/events?events=LocalChangeDetected,RemoteChangeDetected and report back. When I use /rest/events, the LocalChangeDected and RemoteChangeDetected never showed up.

**Comment by AudriusButkevicius** [comment]
Yes, this is working as intended, the docs are probably just outdated.

**Comment by mjyu51** [comment]
Is there a special reason why  LocalChangeDected and RemoteChangeDetected will never show up in /rest/events?

**Comment by AudriusButkevicius** [comment]
Because there is a lot of these events, and they force other more meaningful events to roll off.

**Comment by mjyu51** [comment]
I see, it is a one event/file scenario. That means if I copy/paste 1000K files, it will generate 1000K events and this can flood the event pipe.
This information is very important. We do prefer to have it (all files changed, in a list)

**Comment by calmh** [comment]
FWIW the same reasoning should affect ItemStarted/ItemFinished which we for some reason allow on the default event subscription. (IMHO they should be removed from there)

**Comment by AudriusButkevicius** [comment]
Yeah, fair point.

**Comment by canton7** [comment]
If you do decide to remove be those, give me some warning first please, as I'm relying on them being there.

**Comment by calmh** [comment]
@canton7 I suggest specifying the events you want, regardless, starting now. Older syncthings will ignore the `events` parameter and do what they always did, current and future will give what you expect regardless of whether we change the default.

**Comment by mjyu51** [comment]
@calmh, I wanted to make sure I understand your note correctly:  when you said change the default, you are removing these events from default subscription (using /rest/events without specifying event type). But I still have the chance to get events such as LocalChangeDetected/RemoteChangeDected/ItemStarted/ItemFinsied by subscriptions specifying the type= LocalChangeDetected/RemoteChangeDected/ItemStarted/ItemFinsied?
These type of information is very important for some applications.
