### ISSUE TITLE
documentation about global discovery servers and ssl usage

### ISSUE THREAD

**Issue by l-jonas** [syncthing/docs#427]
For the discovery servers, only domains are specified at <https://docs.syncthing.net/dev/infrastructure.html#global-discovery-servers>. At the example for queries, HTTPS is used (<https://docs.syncthing.net/specs/globaldisco-v3.html#queries>) and <https://discovery.syncthing.net/> and <http://discovery.syncthing.net/> provide different contents (http a default page from nginx, https a not found message). So I guess that HTTPS is required. However, when using https, there is no valid certificate and the documentation says nothing about an https requirement and nothing about the certificate validation.

**Comment by l-jonas** [comment]
@luckywilliams I think that this is known already because https://syncthing.net/ uses it

**Comment by calmh** [comment]
Syncthing uses the "device ID" mechanism to verify the discovery servers, with the ID in question being part of the URL in the Syncthing config. There is some discussion of this in the certificates section of https://docs.syncthing.net/users/stdiscosrv.html

**Comment by l-jonas** [comment]
@calmh It would be a good idea to add these device ids of the public discovery servers somewhere in the documentation. Or at least to add an link to the source code which contains the default config. Background: Syncthing Lite currently accepts all server certificates which looks wrong to me.

**Comment by luckywilliams** [comment]
@l-jonas than I think the https://discovery.syncthing.net/ subdomain is not covered in certificate by your server you can force main certificate on all sub domain or on this particular one by whichever technology your server support like htaccess on apache.

After that if still you get not found error with valid certificate than that will sub domain configuration or redirection issue fit that.

**Comment by calmh** [comment]
@luckywilliams There is nothing wrong with the server configs. We are not troubleshooting anything here. Stand down.

@l-jonas Mmmyeah maybe. That would make it a locked-in official API of sort. While I don't foresee the need to change the certs/IDs in the near future, we've done so historically for various reasons so I'd rather not. They are [in the code](https://github.com/syncthing/syncthing/blob/add12b43aa0bdf5e67d8f421c57a5ecafb3d25fa/lib/config/config.go#L50-L64) for the curious.
