### ISSUE TITLE
Contributions: Android Termux option

### ISSUE THREAD

**Issue by vackosar** [syncthing/docs#438]
It would be very good to highlight also option to use android's app Termux package manager to install syncthing option. It relies on your original code, so I think it is more stable.

**Comment by imsodin** [comment]
Not sure what you mean by the last sentence, but if Syncthing has been added to a termux packager manager (didn't know that exists), that's nice - a PR adding that is welcomed.

**Comment by calmh** [comment]
Unclear as is, but as noted - additions to contributions are via PR
