### ISSUE TITLE
Update building instructions

### ISSUE THREAD

**Issue by otbutz** [syncthing/docs#441]
The current instructions don't work as go modules don't work for the suggested location: `$GOPATH/src/github.com/syncthing/syncthing`

**Comment by imsodin** [comment]
It's no longer necessary, but I am still developing and building at `$GOPATH/src/github.com/syncthing/syncthing` just because I didn't have a good reason to change that, and it works.

**Comment by otbutz** [comment]
Just tried to do a fresh build with go 11.5 in Windows and it only worked after i moved the directory.

**Comment by calmh** [comment]
This was updated a while ago
