### ISSUE TITLE
Configuration option "autoAcceptFolders" for devices isn't documented

### ISSUE THREAD

**Issue by dhs-rec** [syncthing/docs#442]
Reading the configuration via REST API call (and also in the UI), I see in the output that each device has an "autoAcceptFolders" option, set to false. However, I couldn't find it in the documentation.

So what exactly happens if I set this to true?
- Where are automatically accepted folders stored?
- What are their names?

**Comment by AudriusButkevicius** [comment]
They are stored at the default path, and name I think is folder name advertised by remote peer, if that is taken then its folder name plus folder id.

**Comment by AudriusButkevicius** [comment]
Feel free to update the docs :)

**Comment by dhs-rec** [comment]
Well, if you only "think" what it does, how should I know? Do you really want me to update the docs with some half-baked knowledge?

**Comment by AudriusButkevicius** [comment]
For the directory name, it tries folder label, if that exists already on the filesystem it uses the id, if the id exists as well, it doesn't do anything and just logs that it failed.

If you already have a syncthing folder with that id, it just shares it, oppose to creating a new one.

**Comment by stamepicmorg** [comment]
[from sources](https://github.com/syncthing/syncthing/blob/6db8dc33f2a346e5828a6bc92b3e70e66d853494/lib/model/model.go)
```
// handleAutoAccepts handles adding and sharing folders for devices that have
// AutoAcceptFolders set to true.
```

-----------

bump!

**Comment by AudriusButkevicius** [comment]
The documentation is community maintained, so instead of bumping, I suggest you open a PR improving it.
I am more than happy to help with the wording and explanation of how it works in a PR.

**Comment by stamepicmorg** [comment]
> The documentation is community maintained, so instead of bumping, I suggest you open a PR improving it.

it's all very cool. already written above - do I need to learn the "go" language to read the sources and write the documentation?
there is an undocumented thing that the developers are silent about. what to do in this case?

**Comment by AudriusButkevicius** [comment]
The docs repo (the repo you are commenting on) is not go code, it's .rst which is widely documented format for documentation.
There is enough prior art of rst in this repo to deduce how to add a sentence about this setting.

What this setting does is already discussed in this ticket. A pull request adding a description does can be further iterated on, if it does not reflect reality of what the flag does.
