### ISSUE TITLE
Edit on GitHub 404's

### ISSUE THREAD

**Issue by andrewl33** [syncthing/docs#445]
"Edit on Github" at the top right of documentation pages contains a URL in the format "https://github.com/syncthing/docs/blob/master*" instead of "https://github.com/syncthing/docs/blob/master/*".  

Example:
Page: https://docs.syncthing.net/v1.1.0/
Current Edit URL: https://github.com/syncthing/docs/blob/v1.1.0index.rst
Correct: https://github.com/syncthing/docs/blob/v1.1.0/index.rst

Building the documentation on my own computer seems to work fine.

**Comment by calmh** [comment]
Yeah it's broken. Looks like the edit-on-github thing is conflicting with the multiple-versions thing when it builds the github path based on the current page url :(

**Comment by calmh** [comment]
Fixed a while back by removing the version awareness stuff
