### ISSUE TITLE
systemd hardening doesn't work on OpenVZ

### ISSUE THREAD

**Issue by Lillecarl** [syncthing/docs#447]
Might be worth noting in the systemd guide in the docs that the hardening doesn't work in case you're using a superold kernel like 2.6.32-openvz-042stab120.18-amd64

**Comment by calmh** [comment]
We don’t generally make notes on specific obsolete systems or decade old kernels. I mean, I’m sure it could be helpful for someone at some point, but who’s going to maintain the list, what does it mean that kernel 2.6.33 isn’t on it, etc. So no, I think the burden is on the user of obsolete systems to know where they are behind the curve.

On 11 Apr 2019, at 18:09, Carl Hjerpe <notifications@github.com<mailto:notifications@github.com>> wrote:


Might be worth noting in the systemd guide in the docs that the hardening doesn't work in case you're using a superold kernel like 2.6.32-openvz-042stab120.18-amd64

**Comment by Lillecarl** [comment]
Well a good compromise might be to change https://github.com/syncthing/syncthing/blob/master/etc/linux-systemd/system/syncthing%40.service#L13 to something like "#hardening, might not work on old systems"

There's alot of people using cheap VPS's on OpenVZ still, because that's what available for close to no money until Canonical hardens LXD enough for VPS providers to use.

Thanks for the quick reply!

**Comment by calmh** [comment]
Sure. There’s also a hilarious bug in old systemds where it makes /home read only instead of /usr. But the user would need to already be looking at the smoking gun to note the comment.
