### ISSUE TITLE
Unhelpful "last updated" timestamps at the bottom of each page

### ISSUE THREAD

**Issue by vincentardern** [syncthing/docs#459]
The bottom of each page in the docs has a timestamp for when the docs were last updated. This seems unhelpful as each page may be years out of date but a typo was fixed recently on an entirely different page, and thus the docs claim to have been updated recently. This seems misleading, and almost certainly leads users to thinking that the docs are up to date when they're not.

I suggest a way to fix this would be to have the time that an individual page was last updated. Optionally it could also be a two part line with the first part referring to the current page and the second part referring to the global docs.

**Comment by AudriusButkevicius** [comment]
Sadly this is how sphinx works, if you know what configuration we need to change to achieve what you suggested, please open a new issue, otherwise I think there is not much we can do. I don't think we should be forking a documentation framework to address this.
