### ISSUE TITLE
Relay spec: optional port?

### ISSUE THREAD

**Issue by MariusVolkhart** [syncthing/docs#488]
The relay spec for the `SessionInvitation` message indicates that the address and port are optional. An optional address is clear to me - the address length could be `0`, and the spec defines default behavior for when the address is undefined.

However, how an optional port works is not clear to me, given that it is a single `unsigned int` in the protocol. Does a value of `0` indicate "I'm not providing a port number"? How should compliant clients select the port when the remote indicates "I'm not specifying a port". Or is the port, in fact, not optional?

https://docs.syncthing.net/specs/relay-v1.html#sessioninvitation-message-type-6

**Comment by calmh** [comment]
I don't think the client ever sends the invitation, that comes from the relay server. In the code it doesn't look like the port number is in fact optional -- if it's zero we'll try to connect to port zero. The server sets both the address and port to it's listen socket.

The documentation on this isn't particularly clear. I tried to read it now and didn't come away from it much wiser. The [session mode section](https://docs.syncthing.net/specs/relay-v1.html#session-mode) says the client should send the `SessionInvitation` message, but I think it means a `JoinSessionRequest`.

🤷‍♂
