### ISSUE TITLE
Missing guidelines for resolving various out-of-sync problems

### ISSUE THREAD

**Issue by xarx00** [syncthing/docs#500]
In the forums there are plenty of requests on how to resolve an out-of-sync problem or a similar type of problems. There's missing a clear guide (or maybe even tools) on what to do when this happens.

**Please, extend the documentation with clear guidelines on how to resolve such situations.**

The out-of-sync and similar problems (i.e. e.g. locally-changed-items) may occur in multiple situations, and each such situation requires probably a different approach in order no data are lost. These problems may occur as a result of an error (e.g. disk is full, an error in Syncthing code etc.), or naturally as a result of a sequence of user actions (for instance device is unavailable, or after changing folder type from send-receive to send-only, or after modifying content of the receive-only folder). The out-of-sync problems may occur at various stages of the synchronization chain - in the source folder, in the sending device, in the receiving device or in the target folder.

There is necessary a comprehensive guidance for all these distinct situations.

Currently, there is often given only one advice - reset or remove the index. This is advised even in the FAQ. But there is missing a warning, that this operation may corrupt your data! Once the index is deleted, Syncthing may show plenty of out-of-sync items, and the user may get into an even worse situation than he was before!

So please:

- Develop tools that help resolving these out-of-sync problems. A far as I know, there are only two available now: resetting the index, and the RevertLocalChanges red button.
- Create guidelines describing steps to follow when resolving out-of-sync problems.
- Describe negative side-effects of the recovery procedures. E.g. loosing the information where each file was located (after resetting the index), loosing files (after reverting local changes) etc.

**Comment by ProactiveServices** [comment]
Please use the [forum](https://forum.syncthing.net/) for discussion, where you can showcase your suggestions, ask for input, and pool other people's experiences.

**Comment by AudriusButkevicius** [comment]
Also, documentation is community maintained, so feel free to contribute whatever guides you feel are necessary.

**Comment by xarx00** [comment]
There are plenty of ideas for this document in e.g. in the following thread:
https://forum.syncthing.net/t/how-to-accept-local-changes/14657/68

**Comment by xarx00** [comment]
@AudriusButkevicius  I have no problems to contribute, if only I knew the answers :-).

**Comment by AudriusButkevicius** [comment]
This issue tracker is mostly for bugs and features in the application, not documentation.

Also, there is no point having issues open if nobody is planning to work on it.

**Comment by xarx00** [comment]
Nobody shall plan working on that if there is no recorded need/request.
But OK, you're in the charge, I'm a mere passer-by :-).
