### ISSUE TITLE
users/autostart "may be outdated and requires review"

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/docs#523]
I have a question regarding the

>This page may be outdated and requires review.

warning on https://github.com/syncthing/docs/blob/master/users/autostart.rst. As far as I can see, the warning has been present on the page since at least 2015. Does it still stand? I believe that the Windows part is very up-to-date right now, but are the macOS and Linux sections outdated?

If yes, then what do you think about placing the warning(s) in each of the two sections separately rather than addressing the whole page? Right now, the first impression is that the whole page may be irrelevant and should not be followed, which is not the case (at least when it comes to Windows).

**Comment by imsodin** [comment]
After a quick glance I agree the content I know about look good (don't know supervisord or mac). And I think that warning is pretty useless anyway. If there's distinctly outdated info, it should be removed instead. That banner doesn't help anyone in my opinion.

**Comment by tomasz1986** [comment]
Thank you for sharing your opinion. Will be be fine if I do a PR to remove the warning? Please let me know if there are any objections.
