### ISSUE TITLE
Allowing to group the list of folders and of machines in categories  

### ISSUE THREAD

**Issue by hadn** [syncthing/docs#530]
Allow to group folders and machines in categories and possibly show them in a tree-like (hierarchical) visualization. This is important to help manage several projects with many folders and machines in each one of them.

**Comment by AudriusButkevicius** [comment]
This is the documentation repo, but I think there already exists a ticket like this in the application repo, so please use the search.

**Comment by hadn** [comment]
Issues wrongly opened here. It is placed now as a development-request issue in the main project
