### ISSUE TITLE
dev/issues: Missing labels in Issue Management

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/docs#559]
https://docs.syncthing.net/dev/issues.html

I am trying to update the labels to match the actual labels used in the GitHub repository. I have added a short explanation to each one of them, but I am not sure whether they are adequate, so please let me know if different words should be used.

However, there seem to be a few labels that seem not to be used anymore, e.g. `pr-merged` last used in 2018. Should these labels remain in the Docs, or should they be removed? Also, the `unreleased` label has not been used at all, and is not listed in the Issues on GitHub either. Should it remain in the Docs?

This is my sketch for now:

```
api
    Issues related to the API and configuration.

bug
    Issues verified to be a bug.

build
    Issues caused by or requiring changes to the build system (scripts
    or Docker image).

dependencies
    Pull requests that update a dependency file.

documentation
    Issues related to the documentation.

enhancement
    New features or improvements of some kind, as opposed to a problem
    (bug).

frozen-due-to-age
    Set automatically on issues when they have been closed untouched
    for a long time, together with being locked for discussion.

good first issue
    Good starting points for new contributors, contained in scope and
    size, and clear about what is the desired outcome.

needs-triage
    New issues needed to be validated.

not-our-bug
    Rare and temporary label used only when we want to keep an issue
    open for visibility, but the real problem is somewhere else.

pr-merged
    Pull requests merged to the main tree.

protocol
    Issues that require a change to the protocol.

skip-changelog
    Issues minor enough not to be included in the changelog.

ui
    Issues related to the graphical UI.

unreleased
    Set on bugs that have never been in a released stable version, i.e.
    a bug introduced in v1.8.0-rc.1 and fixed in v1.8.0-rc.2, and as
    such excluded from the release notes for v1.8.0.

waiting-for-info
    Issues that require more information on how to reproduce.
```

**Comment by imsodin** [comment]
While some are rarely used, I think only the two you noticed are actually obsolete: pr-merged was used by the old merge-bot if I remember correctly. And skip-changelog replaced unreleased, i.e. unreleased can go. And skip-changelog is mainly used in the scenario you described on unreleased. I don't think we ever set it for "minor" issues. One more use-case that makes sense but I am not entirely sure whether it applies are issues that aren't actually bugs/feature requests (typical support/questions) - @calmh?

**Comment by calmh** [comment]
I think those don't get any tags because they are not actionable or long lived

**Comment by tomasz1986** [comment]
> One more use-case that makes sense but I am not entirely sure whether it applies are issues that aren't actually bugs/feature requests (typical support/questions)

I think that `skip-changelog` has already been used like that, e.g.

https://github.com/syncthing/syncthing/issues/6772
https://github.com/syncthing/syncthing/issues/6788

Should this usage also be included in the Docs?

**Comment by imsodin** [comment]
I think that was me with incomplete information, thus not enough as a precedent. However I think it's good we talk about it and document it - consistent usage of tags is nice.  
To me tags have two purposes: Categorization for filtering/handling outstanding issues and changelog generation, the latter being Jakob's domain (and scripted afaik). Whatever works for the latter is fine with me. Issue reports that are questions/support requests could either have no tags or be closed while still having `needs-triage`, though for scripting it is likely nice when it's the same always.

**Comment by calmh** [comment]
So what happens now change log / scripting wise is the following:

- there's a milestone for each release
- I have a script that I run manually that looks through commits for "fixes #xxx" style notes and adds them to the milestone I specify 
- I sometimes add manual description of important changes to the milestone itself
- the change log for a release comes from the milestone description plus the issues added to that milestone, minus those tagged skip-changelog. 
- the issues are categorized as enhancements or bug or everything else based on the labels. 

So issues that are closed but not added to a milestone are never looked at and I don't care about the labels from that standpoint. It would seem likely that most such issues will still have the needs-triage label when closed.

**Comment by calmh** [comment]
And skip-changelog should only be used for bugs introduced in an RC, which don't need to be mentioned in the change log because they weren't present in any previous version

**Comment by tomasz1986** [comment]
I have pulled a request with the updated changes. If it is accepted, would be OK if I add the descriptions to the actual labels in the main repository? Right now, most of them have no descriptions at all.

![image](https://user-images.githubusercontent.com/5626656/90337385-1fc68a00-e01d-11ea-84b9-633325f5d2d3.png)

**Comment by calmh** [comment]
Yeah that would be neat
