### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rumpelsepp** [syncthing/docs#56]
Just noticed that the docs do not include any license. Here is a list of a few documentation licenses: https://en.wikipedia.org/wiki/GNU_Free_Documentation_License#Other_free_content_licenses

**Comment by calmh** [comment]
The syncthing repo had this

```
License
=======

All documentation and protocol specifications are licensed
under the [Creative Commons Attribution 4.0 International
License](http://creativecommons.org/licenses/by/4.0/).
```

when the docs lived there. I'll re-add that here.

**Comment by rumpelsepp** [comment]
:+1:

**Comment by calmh** [comment]
That said, I'm not sure if it would be better to just put in the public domain straight off the bat

**Comment by calmh** [comment]
OTOH that would be a license change at this point, and I'm not doing that.

**Comment by calmh** [comment]
1871865

**Comment by marclaporte** [comment]
@calmh  bad experiences with license changes? :-)

**Comment by calmh** [comment]
Haha, no so much bad experience as more experience than I'd wanted.

**Comment by marclaporte** [comment]
:-)
