### ISSUE TITLE
"Bitstream Charter" font causes issues with JoyPixels on Chrome

### ISSUE THREAD

**Issue by sk22** [syncthing/docs#565]
* Chrome Version 84.0.4147.125 (Official Build) (64-bit)
* GNOME 3.36.4 on X11
* Fedora 32 (Workstation Edition)

On my Google Chrome, the docs are rendered like this:

![image](https://user-images.githubusercontent.com/6217438/90691018-edae6580-e272-11ea-9864-ff2a197e6f6b.png)

When I remove "Bitstream Charter" from the font-family CSS property, it renders as expected:

![image](https://user-images.githubusercontent.com/6217438/90691546-c6a46380-e273-11ea-9748-62b510725f32.png)

I'm not sure why this issue occurs, what "Bitstream Charter" has to do with JoyPixels, nor why removing "Bitstream Charter" resolves it.

In fact, I can remove every font except "Bitstream Charter" and still see the same problem occur:
![image](https://user-images.githubusercontent.com/6217438/90691796-3f0b2480-e274-11ea-9214-c2d5f29226b2.png)

Removing "JoyPixels" from my machine also solves the problem, but I don't want to remove my emoji font for a single website to be displayed properly. Also, Firefox doesn't appear to be affected by this problem.

**Comment by AudriusButkevicius** [comment]
I don't think we'll fix this. I think its best if you take it up with joypixels as that's the odd one out, it works fine for everyone not using that, so that must be the cause.
