### ISSUE TITLE
Explain case insensitive filename handling

### ISSUE THREAD

**Issue by acolomb** [syncthing/docs#566]
There is very little information in the docs about what Syncthing does to avoid or handle case conflicts. The [advanced configuration section](https://docs.syncthing.net/advanced/folder-caseSensitiveFS.html) only says "Syncthing will attempt to detect and prevent case-only file name collisions that can occur on case insensitive systems", but not any scenario or algorithm what is handled and what leads to conflicts.

Thought this might serve as a reminder to document the behavior while it is still fresh in mind after the v1.9.0 release.

**Comment by imsodin** [comment]
What exactly would you want documented? From a user perspective it shouldn't need any explanation. While the previous behaviour was "we don't care about case conflicts, just make sure there aren't any and if they still occurs, there's some weird workarounds to get it working again" it is now "case conflicts can still occur, if they do we will notify the user in the web UI with a descriptive and understandable message (hopefully, if not that needs improving)". I don't see how explaining what we do exactly at a low level to catch the case conflicts isn't of any value to the user in my opinion.

**Comment by calmh** [comment]
The intention is that there should be no user surprises here. If you sync between case sensitive filesystems you can have file names that differ just in their case and not notice anything. If you sync between case insensitive filesystems things should also work as expected, including when changing only the case of an existing file. If you try to sync multiple files that differ only in case from a case sensitive system to a case insensitive one, the case insensitive system will show a sync error due to file name collisions.

**Comment by acolomb** [comment]
I am missing some end-user explanation on what will happen in the following scenarios (list not exhaustive). Assume devices A and B, each at the default settings `caseSensitiveFS = false`.

* A and B have a file (or folder, shouldn't matter) called `BAR` and `bar` respectively, pre-populated when setting up a shared folder. I assume they will both show a sync error? Or will they just compare it regardless of case difference?

* On A, the file is renamed to `Bar`. Will this cause B to try renaming the existing file?

* On B, the file is renamed to `Bar` as well. Will the sync error disappear, if there was one? On which side?

* When already in sync, will a case-only rename be propagated to the other devices?

* If B is set to `caseSensitiveFS = true` instead (matching its actual filesystem), will renaming `Bar` to `bAR` there be propagated to A as a case change of the existing file or possibly lead to an error because the added file `bAR` conflicts with the existing, to-be-deleted `Bar`?

Taking into account more than two devices, as well as a mix of case-sensitive and insensitive ones, there are of course many more possible scenarios.

Some of these questions are actually more about the case *preserving* behavior of Syncthing. There must be some notion of the "correct" case spelling in the database I assume, so how is that defined and under what cirumstances will it be synced / applied to other devices' file systems?

An overview of what defines the "common global state" in light of case differences would be a good start.

**Comment by imsodin** [comment]
What would you expect solely based on "no surprises"? Excluding anything involving a change of `caseSensitiveFS` I am somewhat confident that you'd get it right. And that's sort of the point. We don't believe we need to tell anyone about it in advance. If they just do whatever, it will turn out right. And adding more devices doesn't change that. Based on your questions about db, case-preserving and common global state, I believe you are overthinking this. There's no "correct" case, nor other magic. A different case is different file, contributing to the global state the same way it did before. If a filesystem can't have two different files only differing by file, an error notifying the user of a case-conflict will appear.

**Comment by acolomb** [comment]
> A different case is different file, contributing to the global state the same way it did before. If a filesystem can't have two different files only differing by file, an error notifying the user of a case-conflict will appear.

Okay, that sounds like a good starting point for an overview description. I'd suggest something like this explanation in the docs then:

---

Syncthing always regards and compares path names in a *case sensitive* way between devices. Two files (folders) with different case on different devices will result in two disparate entries in the "global state". With `caseSensitiveFS = false`, one of them *(or both?)* will be reported as conflicting even when they are otherwise identical. However, any other device configured `caseSensitiveFS = true` will happily pull both, leading to local duplication. Local files only match an entry from a remote device if they have exactly the same case spelling.

---

Another scenario involving three devices, which is unclear to me:
* Cluster consisting of A -- B -- C, with no direct link between A and C. Device B learns from A about a file called `BAR` and from C about a file called `bar`. As they are completely separate, it's undefined which one is "newer". Will B pull from A or C? Or just bail out and pull neither variant to the local device? The latter would be a "suprise" to the user, because most other software will just find the same contents and live with the different file name case.

* In the scenarios above where one device does a case-only rename, will the other case-insensitive devices handle that efficiently (change case of the existing file or folder), or will they delete the old and re-pull the new variant? Since the two variants cannot coexist locally, even reusing blocks becomes hard. If the case-only rename happens at the top level of a large folder hierarchy, that might be a "surprise" to the user, since most other software will happily keep using the files within regardless of file name case change -- but Syncthing would possibly delete and re-create the whole hierarchy?

**Comment by imsodin** [comment]
That's wrong though. And again the questions are besides the point, trying to reason about mechanisms that don't exist. Syncthing always was and still is case sensitive. Two files like "foo" and "Foo" are completely different from the point of view of Syncthing, both now and before the recent change to handle case-insensitive filesystems. The following is trying to explain to *you* what's going on, because you clearly care. I maintain this is not knowledge that a user needs.

The basic change that happened was that now the filesystem checks that when Syncthing calls a function for file "foo", it really gets info on "foo". That's not given on case-insensitive filesystems, where the filesystem happily gives you information on "Foo" when asked about "foo", pretending the file is really called "foo". We put a wrapper on the filesystem, which before asking the filesystem for "foo", checks what really exists on the dir. It first directly askes about "foo", and then checks the directory contents. If it gets a positive result for "foo", but then sees that only "Foo" but not "foo" exists, it returns an error (because the fs is case-insensitive and "lying" that "foo" exists). That's the change that matters. When the case-sensitive Syncthing now asks the filesystem about a file, it always gets a case-sensitive answer, even when the underlying filesystem isn't case-sensitive.

And that wasn't a rhetorical question:

> What would you expect solely based on "no surprises"?

So let me answer what no surprises means to me:

>     * A and B have a file (or folder, shouldn't matter) called `BAR` and `bar` respectively, pre-populated when setting up a shared folder. I assume they will both show a sync error? Or will they just compare it regardless of case difference?

If the underlying filesystem is case-sensitive, they will both have both files after syncing. If the underlying filesystem is case-insensitive, there will be an error displayed in the UI, because Syncthing can't sync the other file they don't have yet.

>     * On A, the file is renamed to `Bar`. Will this cause B to try renaming the existing file?

Same as above. Either rename or error (error now on "Bar", no longer on "BAR").

>     * On B, the file is renamed to `Bar` as well. Will the sync error disappear, if there was one? On which side?

Now everyone has "Bar" and "Bar" only, there's no errors.

>     * When already in sync, will a case-only rename be propagated to the other devices?

Sure.

And that's what's happening now.

**Comment by acolomb** [comment]
> That's wrong though. And again the questions are besides the point, trying to reason about mechanisms that don't exist.

Sorry, what part exactly is wrong? Did I draw wrong conclusions in the suggested documentation paragraph?

> Syncthing always was and still is case sensitive. Two files like "foo" and "Foo" are completely different from the point of view of Syncthing [...]

This basic fact is not mentioned in the docs, hence this issue. For a large portion of the user base (Windows platform), it's also unusal / counterintuitive, as they are used to software being case-preserving but not case-sensitive. I'm just saying that we should document at least this basic principle, enriched by some examples of the consequences. I'd be happy to contribute such a paragraph when it's deemed factually correct.

> The following is trying to explain to _you_ what's going on, because you clearly care. I maintain this is not knowledge that a user needs.

Thank you for the technical explanation, that's pretty much what I gathered from the various related issues and PR discussions.

> And that wasn't a rhetorical question:
> > What would you expect solely based on "no surprises"?

After knowing that it is case-sensitive, basically what you described. However: IIRC, older Syncthing versions would happily sync a the contents of folder "BAR" on A with the folder "bar" on B, as long as no case-sensitive device was involved, right? From that experience one could have "learned" that it was case-insensitive, so now getting an error in the same situation would be a surprise. For me *personally*, the errors displayed would be expected behavior. It might still be an inconvenience, but that's a totally different issue. Other people would be surprised by that inconvenience because they might not even be aware of case differences at all.

Some background info why I think it's important to mention, from real world experience (before v1.9.0): a large CAD software *sporadically* decided to convert all path and file names to lowercase when saving changes. Two colleagues wanted to merge their `CAD` and `cad` folders into a common Syncthing-shared project folder. The contents were merged on both sides, making Syncthing look case-insensitive. One central Linux-based node happily aggregated both variants separately. A third person pulling from there to a Windows machine again got one of the two variants plus a cryptic error message for the other -- which is now improved in v1.9.0. Nobody did anything wrong here, so if Syncthing still (rightfully) shows an error message, the reason should be comprehensible from the provided documentation.

Could you please explain the additional two scenarios from my [last comment](https://github.com/syncthing/docs/issues/566#issuecomment-690358384) as well?

**Comment by imsodin** [comment]
>     * Cluster consisting of A -- B -- C, with no direct link between A and C. Device B learns from A about a file called `BAR` and from C about a file called `bar`. As they are completely separate, it's undefined which one is "newer". Will B pull from A or C? Or just bail out and pull neither variant to the local device? The latter would be a "suprise" to the user, because most other software will just find the same contents and live with the different file name case.

I need to know whether the actual file system is case-insensitive or not, otherwise  the scenario is not well-defined. I assume they all are case-insensitive. Then B will successfully sync the first file it encounters, and report an error on the second, as it fails to create it on disk due to a case-conflict.

>     * In the scenarios above where one device does a case-only rename, will the other case-insensitive devices handle that efficiently (change case of the existing file or folder), or will they delete the old and re-pull the new variant? Since the two variants cannot coexist locally, even reusing blocks becomes hard. If the case-only rename happens at the top level of a large folder hierarchy, that might be a "surprise" to the user, since most other software will happily keep using the files within regardless of file name case change -- but Syncthing would possibly delete and re-create the whole hierarchy?

It will be renamed efficiently (at least in 1.10.0, there was a bug preventing that) and even without that, block reuse is not an issue, because we use temporary files (the steps in puller will be: copy blocks to temporary file, fail to final name rename because case conflict, delete the old file, reuse temporary file, rename again, successfully).

I am not against documentation in general, I just believe/hope this problem should be understandable without documentation, the error being enough. Looking at the support thread that just came up, I think the current error message isn't good enough. And that's what I'd like to improve. Because 99.9999% of users will not go search the documentation when encountering an error (and definitely not in advance to "be prepared"), neither should they have to.  
First question: Where would such information go? Maybe the "Understanding Synchronisation" section?

**Comment by acolomb** [comment]
> I need to know whether the actual file system is case-insensitive or not, otherwise the scenario is not well-defined. I assume they all are case-insensitive. Then B will successfully sync the first file it encounters, and report an error on the second, as it fails to create it on disk due to a case-conflict.

Yes I meant B to be case-insensitive. So it's not deterministic which version ends up locally and which one is marked as an error. That's an important fact I suppose.

> I am not against documentation in general, I just believe/hope this problem should be understandable without documentation, the error being enough. Looking at the support thread that just came up, I think the current error message isn't good enough. And that's what I'd like to improve. Because 99.9999% of users will not go search the documentation when encountering an error (and definitely not in advance to "be prepared"), neither should they have to.

I see several points that would be too much for the error message and hence should be found in the documentation. Linking to the docs from the error message would give usability bonus points :-)

1. What principle does Syncthing follow regarding file name case? >>> case-sensitive (contrary to what Windows users expect, which is only case-preserving), give some examples to explain what happens.

2. What is the root cause for said error message? >>> Files on different nodes with only case differences, and your local device not supporting that. Link to the advanced config option page for the case you know better and accept the risks.

3. How to remedy this situation? >>> Make sure to have only one version of file name case across all devices, **manually**. That's actually not an easy task so understanding why Syncthing cannot handle it automatically would be important to explain.

> First question: Where would such information go? Maybe the "Understanding Synchronisation" section?

That was my first thought as well, but only if it's kept rather terse. Alternatively, put it under the FAQ so the answer you gave in the [thread](https://forum.syncthing.net/t/given-name-xyz-differs-from-name-xyz-in-file-system-error/15605/10) (point 3 above) is easy to discover. Counting all threads before the behavior was defined for v1.9.0, I'd say "Syncthing and path case problems" is a frequently occurring topic.

**Comment by acolomb** [comment]
> Syncthing always was and still is case sensitive.

Re-reading the [original design proposal](https://github.com/syncthing/syncthing/issues/2739), I think it contradicts this statement. Was the design changed since then, to keep different case versions in the index as separate entries?

**Comment by acolomb** [comment]
See https://github.com/syncthing/syncthing/issues/6993 and https://github.com/syncthing/syncthing/issues/6989 for why I think this should be documented. The basic assumptions are not clear and obviously unexpected for some people.

I volunteer to write this up as a docs PR, but the open questions above need answers first.

**Comment by imsodin** [comment]
> Re-reading the [original design proposal](https://github.com/syncthing/syncthing/issues/2739), I think it contradicts this statement. Was the design changed since then, to keep different case versions in the index as separate entries?

The original design isn't what was implemented in the end. If you want to dive deep a possible starting point is the wiki: https://github.com/syncthing/syncthing/wiki/Untrusted-devices-(encryption)-status  
The underlying principle is that Syncthing is case sensitive (which is true before and after the recent case-insensitivity related changes). Previously the behaviour of case-insensitive filesystems and the API to interact with the FS was incompatible with that principle, leading to various problems. This behaviour is now checked, such that we detect case conflicts and either handle them or present an error about a case conflict to the user.  
If you'd document that Syncthing's case-sensitivy, in nicer/more understandable terms, maybe along with some example scenarios, I'd very much welcome that.  
I believe this has already been made clear in another issue, but just to be sure: The `caseSensitiveFS` has nothing to do with that. It shouldn't be mentioned in such a discussion, as it must not be used in general. It's not a different, also valid mode, it's just an optimisation that may be used in some circumstances. Used in the wrong circumstances it will bring back all the pesky case-related problems and bugs.

**Comment by acolomb** [comment]
Here goes: https://github.com/syncthing/docs/pull/568

I hope it's understandable and most of all factually correct. If anyone disagrees, please comment there.
