### ISSUE TITLE
globbing: syntax error in pattern for SD1/music/ok/Music/Music/mix/Wie Weit [] - Apocalyptica~[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9].mp3 

### ISSUE THREAD

**Issue by koo5** [syncthing/docs#572]
i have a file named `SD1/music/ok/Music/Music/Mix/Wie Weit [] - Apocalyptica.mp3`
i get this notice. i dont know why:) also, i don't have any ignore patterns set.

**Comment by acolomb** [comment]
Please use the [forum](https://forum.syncthing.net) for support requests.

**Comment by calmh** [comment]
This is syncthing/syncthing#2606 which is long running and surprisingly tricky...
