### ISSUE TITLE
Consider removing Syncthing Lite from Community Contributions (and possibly F-Droid and Play Store?)

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/docs#586]
Syncthing Lite has been unmaintained for quite a while. Is it even compatible with the current versions of Syncthing? Last time when I tried using it a few months ago, it kept failing to connect/download files.

If it still works, then nothing should be done, but if not, I would suggest removing it both from the Docs, and also consider removing/unlisting it from F-Droid and Play Store, as right now it appears as if the application was still maintained and fully functional.

What do you think?

**Comment by calmh** [comment]
If it hasn't updated for a long while it's likely not fantastically compatible and could be considered unmaintained.

**Comment by tomasz1986** [comment]
Well, the repo is already "archived", so there is that, but I will try to do one more test in Android 7.1. If it does not work, then I will do a PR to remove it from the Docs.

**Comment by calmh** [comment]
Or move it to the unmaintained section at the bottom, yes. 👍
