### ISSUE TITLE
Clarify comments in stignore files

### ISSUE THREAD

**Issue by endolith** [syncthing/docs#594]
https://github.com/syncthing/docs/blob/main/users/ignoring.rst says:

```
.DS_Store     # ignored, will be deleted if gets in the way of parent directory removal
foo           # ignored, matches "foo"
foofoo        # synced, does not match "foo" but would match "foo*" or "*foo"
bar/          # synced
    baz       # synced
    quux      # ignored, matches "qu*"
    quuz      # synced, matches "qu*" but is excluded by the preceding "!quuz"
bar2/         # synced, despite matching "*2" due to child frobble
    baz       # ignored, due to parent being ignored
    frobble   # synced, due to "!frobble"
My Pictures/  # ignored, matched case insensitive "(?i)my pictures" pattern
    Img15.PNG # ignored, due to parent being ignored
```

but it doesn't say anything about `#` signifying comments, only `//`.  

They are also used here: https://forum.syncthing.net/t/useful-stignore-patterns/1175/69

```
//-vi(m)
(?d)*.*.sw[a-p] # Thankys to Tom Hale!
```

Do they act as comments, too?

**Comment by imsodin** [comment]
`#` isn't special, except when used as `#include`. The first block you cite is a "visualisation" of a filesystem tree, with explanations about which pattern, if any. applies and how - it has nothing to do with ignores syntax. The paragraphs before explain that:

> Given a directory layout:
> 
> [...]
> 
> and an .stignore file with the contents:
> 
> [...]
> 
> all files and directories called "foo", ending in a "2" or starting with "qu" will be ignored. The end result becomes:

**Comment by endolith** [comment]
So the comment in https://forum.syncthing.net/t/useful-stignore-patterns/1175/69 is invalid?

**Comment by imsodin** [comment]
Not invalid, but probably not working as intended. It would ignore e.g. ".something.swb # Thankys to Tom Hale!".
