### ISSUE TITLE
The docs are not clear about what happens to the filename when a hash is used in place of the filename when a filename is too long.

### ISSUE THREAD

**Issue by 93-infinity** [syncthing/docs#657]
Per the docs at https://docs.syncthing.net/users/syncing.html:

>The temporary files are named .syncthing.original-filename.ext.tmp or, on Windows, ~syncthing~original-filename.ext.tmp where original-filename.ext is the destination filename. The temporary file is normally hidden. 
If the temporary file name would be too long due to the addition of the prefix and extra extension, a hash of the original file name is used instead of the actual original file name.

Does the hash of the original file name include the  .syncthing prefixes and the .tmp extension, or the entirety of the filename is just the hash? 

My suggestion:
`If the temporary file name would be too long due to the addition of the prefix and extra extension, a hash of the original file name is used instead of the actual original file name, e.g. .syncthing.[HASH].ext.tmp or, on Windows, ~syncthing~[HASH].ext.tmp`

**Comment by AudriusButkevicius** [comment]
Feel free to update the docs:

```
	tdir := filepath.Dir(name)
	tbase := filepath.Base(name)
	if len(tbase) > maxFilenameLength {
		tbase = fmt.Sprintf("%x", sha256.Sum256([]byte(name)))
	}
	tname := fmt.Sprintf("%s%s.tmp", prefix, tbase)
```

**Comment by 93-infinity** [comment]
If I am understanding you correctly (not programmatically inclined):

>"%s%s.tmp", prefix, tbase

the first %s is the syncthing prefix which varies by platform, the second %s is the "tbase" which is a sha256 hash of the filename, and the extension will be .tmp everywhere, so an example hashed-filename might look like:

.syncthing.894893A05755ECC7F01189B01BA47E5709C6534009EA39ACBE109F76E527BDC1.tmp (non-Windows)
~syncthing~894893A05755ECC7F01189B01BA47E5709C6534009EA39ACBE109F76E527BDC1.tmp (Windows)

Does that seem right?

**Comment by AudriusButkevicius** [comment]
Yes

**Comment by 93-infinity** [comment]
According to the original text the Windows/non-Windows version would have to be listed, then using a hash as an example would make it too verbose. The best I could do is resort to tweaking the text in the last sentence slightly:

Original:
The temporary file is normally hidden. If the temporary file name would be too long due to the addition of the prefix and extra extension, a hash of the original file name is used instead of the actual original file name.

Suggestion1:

The temporary file is normally hidden. If the temporary file name would be too long due to the addition of the prefix and extra extension, the temporary files are named ``.syncthing.original-filename.ext.tmp`` or, on Windows, ``~syncthing~original-filename.ext.tmp`` where ``hash`` is a hash of the original filename.


Suggestion2 (sha256 hash version)

The temporary file is normally hidden. If the temporary file name would be too long due to the addition of the prefix and extra extension, the temporary files are named ``.syncthing.original-filename.ext.tmp`` or, on Windows, ``~syncthing~original-filename.ext.tmp`` where ``hash`` is a SHA-256 hash of the original filename.

**Comment by AudriusButkevicius** [comment]
I think 2 is the best, but I'd encompass the hash as `<hash>`

**Comment by 93-infinity** [comment]
OK that would yield

>The temporary file is normally hidden. If the temporary file name would be too long due to the addition of the prefix and extra extension, the temporary files are named ``.syncthing.<hash>.tmp`` or, on Windows, ``~syncthing~<hash>.tmp`` where ``<hash>`` is a SHA-256 hash of the original filename.

Any need to show an example hash or is that too much?

**Comment by AudriusButkevicius** [comment]
I don't think you need to, the point is that the file name might not be something the user expects.

**Comment by AudriusButkevicius** [comment]
Fixed by https://github.com/syncthing/docs/pull/658
