### ISSUE TITLE
Docs: discosrv - TCP or UDP

### ISSUE THREAD

**Issue by benjaminaigner** [syncthing/docs#66]
Dear all,

your documentation clearly states, that discosrv is using UDP/UDPv6.

If I start discosrv, the netstat command (*netstat -utlp | grep discosrv*)
only shows a TCPv6 LISTEN connection:

*tcp6       0      0 [::]:22022              [::]:*                  LISTEN      3017/discosrv *

Is it possible, that the documentation should be updated?

Best regards,
Benjamin

**Comment by AudriusButkevicius** [comment]
0.11 uses udp, 0.12 uses tcp, so the problem is that we are in-between versions, hence the code does not yet match the docs, as 0.12 hasn't been released.

**Comment by benjaminaigner** [comment]
So the best solution is the TCP setting for the firewall since future versions are using TCP?

**Comment by AudriusButkevicius** [comment]
Well no, the best setting dwpwnds on which version you are using.

**Comment by benjaminaigner** [comment]
I found my mistake:
I took the first download, missing the clue of 0.11 vs 0.12.

Maybe because the latest release of syncthing itself is 0.11 and discosrv has 0.12

Anyway, sry for my mistake.

But maybe it is worth mentioning in the docs.

Regards

**Comment by AudriusButkevicius** [comment]
The old docs will go away when v12 is released in a few days
