### ISSUE TITLE
Show deprecation in the index.

### ISSUE THREAD

**Issue by jtagcat** [syncthing/docs#678]
https://docs.syncthing.net/dev/rest.html

So you find the right thing (system/config) and open it, it's deprecated.

 - Strikethrough the link, and give a pointer to the replacement.

![image](https://user-images.githubusercontent.com/38327267/131230367-7dadb207-7d27-40aa-af0b-2cea0a8641e4.png)

**Comment by calmh** [comment]
👍 that'd be nice

**Comment by acolomb** [comment]
This is not easy to implement fully:

* What we can easily do is just append `(DEPRECATED)` to the document titles, which will obviously also appear in the TOC.
* Adding strikethrough can be done with a little hackery, but I personally think it's uglier than just adding the suffix.
* Arbitrary text linking to a replacement or importing the version changes is not possible with the current `.. toctree::` construct.

I'll make a PR for the suffix thing if @syncthing/maintainers agree on it.

**Comment by calmh** [comment]
Keeping in mind we shouldn’t alter link urls or targets unnecessarily, sure.

**Comment by acolomb** [comment]
@jtagcat since the other parts of your suggestion are unlikely to get fixed (because of technical limitations), OK to close this?

**Comment by jtagcat** [comment]
yea, sure
