### ISSUE TITLE
FAQ: Handling renames of small files? :)

### ISSUE THREAD

**Issue by camoz** [syncthing/docs#699]
The FAQ says:

> Syncthing handles renaming files and updating their metadata in an efficient manner. This means that renaming a large file will not cause a retransmission of that file. Additionally, appending data to existing large files should be handled efficiently as well.

Source: https://docs.syncthing.net/users/faq.html#is-synchronization-fast

Is that only the case for large files, or also for small files? If it also works for small files, can we remove "large" everywhere in the quote above to be more precise?

Also, "should" in "appending data to existing large files should be handled efficiently as well" confuses me a bit: Well now, is it handled efficiently or not?

**Comment by acolomb** [comment]
I depends on your definition of "efficient", hence the "should" I suppose.  For large files, the management overhead is negligible in relation to the data transfer effort.  For small files, not so much.  The explanation sentence could be extended to say that Syncthing applies a content addressing scheme to any data it manages, so identical parts of files (called "blocks") will be reused if possible without transmitting from other devices again.

What is actually missing here is the fact that *efficient renaming* does not mean the `rename()` system call being used, but a separate temporary copy will be made, reusing the blocks from the old file.  So there is a spike in disk usage of about 200 % and it causes some disk I/O for the duplication (depending on your filesystem).  But the network re-transfer is skipped, which is usually considered the slowest / most expensive part.

For appending to files, there are a couple of different cases.  Either the last block is modified, so the efficiency (in a duplicated data transfer sense) depends on how much data was already in that last block.  Or Syncthing decides to add another block for the new data, leaving anything before untouched.  Then it depends on how often this happens, as adding many small blocks to the end will have relatively larger management overhead.  I'm not really certain how exactly this is handled in the code, but I can see reasons why keeping the explanation a bit vague might be more sensible than spelling out all these technical details in a FAQ entry.

If you have any concrete suggestions how this could be explained better (maybe based on my explanation above), feel free to make a PR and we'll see if it's accurate and easy to understand.

**Comment by calmh** [comment]
I think the reason "large" is mentioned is that the whole thing matters less for small files. Did we copy, move or retransfer that 1kb file? Who cares? It's lost in the noise. 

Obviously there's no technical difference in the handling of files based on their size.

**Comment by camoz** [comment]
Okay, what about removing `large` in the description then? I.e. change it from

> Syncthing handles renaming files and updating their metadata in an efficient manner. This means that renaming a large file will not cause a retransmission of that file. Additionally, appending data to existing large files should be handled efficiently as well.

to

> Syncthing handles renaming files and updating their metadata in an efficient manner. This means that renaming a file will not cause a retransmission of that file. Additionally, appending data to existing files should be handled efficiently as well.

IMO it's more clear and precise this way, and a user will surely know on their own that this only matters for large files...

**Comment by calmh** [comment]
Sure

**Comment by zertrin** [comment]
Now that the MR was merged, this issue can be closed I believe 😉

**Comment by camoz** [comment]
Yes I'm fine with that! Thanks @acolomb btw for your long explanation :)
