### ISSUE TITLE
Should display banner when browsing outdated version of the documentation

### ISSUE THREAD

**Issue by calmh** [syncthing/docs#718]
When browsing the documentation and:
1. you're on a specific version URL (`/v1.2.3/*`), and
2. that version is not the latest version
we should show a banner to the effect of you "You're browsing the documentation for Syncthing v1.2.3 which is not the latest version and may be outdated, click here for the current/latest version".

**Comment by acolomb** [comment]
Right now we don't actually have the version string / tag available in the built docs, do we?  Should probably use a similar mechanism as in the main repo to extract it from `git describe`...

**Comment by acolomb** [comment]
Ok so let's skip this until the merger is done, okay?  Then I'll also integrate a version picker directly into the banner.
