### ISSUE TITLE
is it possible to tale an existing directory  and make that synchronize with other member machines?

### ISSUE THREAD

**Issue by Motocycle347** [syncthing/docs#723]
That would be extremely useful. Th e assignment of the dir would replicate on all member machines

**Comment by tomasz1986** [comment]
This is the documentation repository. Please use the forum at https://forum.syncthing.net to ask general questions about Syncthing 🙂.

However, when writing on the forum, I'd strongly suggest to be much more specific and explain in details what you're asking about. For what it's worth, I've got no idea what "tile" is supposed to mean in this context.
