### ISSUE TITLE
Failed to start Syncthing!!!

### ISSUE THREAD

**Issue by WKRZY** [syncthing/docs#774]
![image](https://user-images.githubusercontent.com/40718086/200729574-a911fb56-c8f7-40b0-8f6c-908e9ee2b2e4.png)

I use windows ,what should i do to solve this problem?

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
