### ISSUE TITLE
Caddy V2 reverse proxy

### ISSUE THREAD

**Issue by FilipHarald** [syncthing/docs#784]
Thank you for an awesome application!

I ran in to some problems when setting it up in docker with Caddy V2 as reverse proxy. I'm not sure exactly what is causing it. But Syncthing's docs does not seem to be correct.

[According to Caddy's docs here](https://caddyserver.com/docs/caddyfile/directives/handle_path#examples), `handle_path` is both `handle` and `uri strip_prefix` combined. What ST's docs is currently suggesting does not only seem to be to verbose, [but for me it did not actually work at all](https://github.com/FilipHarald/selfhosted/commit/abab04b8536a370a87dc61a693cc6c329980cacc).

Vaultwarden in this case worked fine before removing `uri strip_prefix` as well though.

PS: starting Caddy with `header_up X-Forwarded-Host {host}` gives a warning that it is already default and therefore not necessary. [Removing that worked for me as well](https://github.com/FilipHarald/selfhosted/commit/4ea0c9ebf430d2687f915f5b0ee946fd0e540ce8).

**Comment by FilipHarald** [comment]
I created a PR where I removed `uri strip_prefix` since `handle_path` already does that.

However, I saw that the `header_up X-Forwarded-Host {host}` was added from this PR #725. And since it is not causing any problems, maybe it is better to leave it.

**Comment by calmh** [comment]
Thanks for fixing!
