### ISSUE TITLE
Document page, perpage, and total parameters of /rest/db/need

### ISSUE THREAD

**Issue by canton7** [syncthing/docs#81]
Seems these aren't documented. For example, which of `progress`, `queued`, and `rest` does the pagination apply to? Will we get some pages where `queued` has many items but `rest` is empty, followed by some where `queued` is empty, but `rest` is many items?

What is `total` the total of?

**Comment by AudriusButkevicius** [comment]
Pagination is union of all of them. Rest usually only shows up when we started pulling a batch but a new index update comes in adding new stuff to pull. Total is sum of all of them available.

**Comment by canton7** [comment]
So `total` is regardless of pagination? If I set `perpage` to 10, will I get 10 `queued` and 10 `rest` items, or just 10 `queued` items (and the `rest` items will appear on a subsequent page), or..?

**Comment by AudriusButkevicius** [comment]
Total is needed to know the number of pages. If you set page 0 and per page 100, you will get 100 entries, if progress has more than 100 it will be 100 items in progress, if progress has less than a 100 say 50, it will start populating queued to achieve a 100, if queued has less than 50, say 30, it will populate 20 from rest. Paging obviously shifts this whole process, so its likely that of you have 10 prog 10 queued and 500 rest, page 2 with 100 per page will only contain rest.

**Comment by canton7** [comment]
Gotcha, thanks.
