### ISSUE TITLE
How to synchronize between different folders on a device? 

### ISSUE THREAD

**Issue by chenyajunai** [syncthing/docs#810]
How to synchronize between different folders on a device? The server hangs network Cloud storage, and directly synchronizes to the network cloud storage mount folder

**Comment by calmh** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
