### ISSUE TITLE
download address for the gpg key is needs update (Debian install page)

### ISSUE THREAD

**Issue by LionelHoudelier** [syncthing/docs#837]
The address for the gpp has changed with "www". Please change the doc page [(https://apt.syncthing.net]:
Old text : sudo curl -o /usr/share/keyrings/syncthing-archive-keyring.gpg https://syncthing.net/release-key.gpg
New text : sudo curl -o /usr/share/keyrings/syncthing-archive-keyring.gpg https://www.syncthing.net/release-key.gpg
Otherwise, it does not download the file but the answer of the server.

**Comment by LionelHoudelier** [comment]
could not find a link for a pull request on that page...

**Comment by calmh** [comment]
Corrected, thanks.
