### ISSUE TITLE
Is JunctionAsDirs working as expected in 1.28?

### ISSUE THREAD

**Issue by Mrnofish** [syncthing/docs#881]
I have a folder that is shared between a Windows machine running SyncTrayzor and an Android device with Syncthing-fork.
- On the Windows side, the folder contains a junction and in the Advanced Settings the folder still has the JunctionsAsDirs flag set to on.
- On the Android device, the junction appears as a folder, but the contents have completely disappeared.
- The size of the folder displayed by both Syncthing clients is smaller than it should be.

Up until a few weeks ago, everything has been working as expected, the Android device has not received Syncthing-fork updates in a while, it's still at 1.27.9 which should be the last version on F-Droid, despite being a few versions behind the official client.

Windows is set to automatically update from syncthing.net and has received 1.28. 1.27.11 came out at the beginning of September, and I think everything was still fine back then.

I tried flipping the JunctionAsDirs flag, rescanning, restarting to no avail.

The SyncTrayzor logs go back to October, 17, while Android has detailed logs until October, 23, but I could find nothing useful. After enabling fs, scanner, walkfs, watchaggregator in the Debugging Facitilies and rescanning again, very little of use:

```
[dev_id] 2024/10/24 time_of_day walkfs.go:84: DEBUG: walk: path=junction_name
```

Am I wrong in thinking something has gone wrong on the Windows client's side recently?

**Comment by imsodin** [comment]
There's a known issue indeed: https://github.com/syncthing/syncthing/issues/9775

In general please report issues on the behaviour of syncthing on the main repo, not here in the docs repo, and if you have questions or want help, please use the forum https://forum.syncthing.net/ - thanks.

**Comment by Mrnofish** [comment]
Apologies, I looked the repo up and didn't notice the search engine had listed the docw one first.

Using the right one would have saved me a good chunk of time, too.
