### ISSUE TITLE
syncthing/syncthing-android /  ‘This app is discontinued’

### ISSUE THREAD

**Issue by d-g** [syncthing/docs#883]
*Youʼve banned outsiders from <https://github.com/syncthing/syncthing-android/issues>, so I have nothing to do but write it here.*

> This app is discontinued. The last release on Github and F-Droid will happen with the December 2024 Syncthing version. Interactions (issues, PRs) are limited now, and the entire repo will be archived after the last release. Thus all contributions are preserved for any future (re)use. [0]

I do not get it.  What ‘future reuse’?

As far as I see [1], @catfriend1 is going to continue his com.github.catfriend1.syncthingandroid [2].

f-droid.org maintainers have already recommended it [3].

Are you on the outs with him?

Or have he rejected your invitation to take the release keys?

Or do you believe, that it is he who must come and humbly propose himself for the maintainership?

[0] https://github.com/syncthing/syncthing-android/commit/4d2384c1ddd6e1f0b8e54b06f619ace35e9d8b46
[1] https://github.com/Catfriend1/syncthing-android/commit/565d629820308a5c2b97d52fe78270a38159cf7a
[2] https://github.com/Catfriend1/syncthing-android
[3] https://f-droid.org/en/packages/com.nutomic.syncthingandroid/

**Comment by imsodin** [comment]
This came up many times, you can find all the answers. Also the right place to ask questions is the forum: https://forum.syncthing.net/

**Comment by d-g** [comment]
> This came up many times

Oh...

> @imsodin closed this as not planned

...so it wonʼt burden you too much to reclose this as a duplicate? ;)
