### ISSUE TITLE
STNORESTART missing in syncthing(1)

### ISSUE THREAD

**Issue by rumpelsepp** [syncthing/docs#94]
The manpage lacks documentation for STNORESTART.

**Comment by lukehamburg** [comment]
Looking for some info on this myself. I am having a problem on macOS where I wind up with 2 daemons running (LaunchServices keeps trying to start a 2nd instance, causing excessive CPU usage and flooding the syncthing log...)

I am trying to come up with the right combo of settings for launchd so that 1 (and only 1) instance of syncthing will run, and it will gracefully recover from a crash, and also properly respond to the "restart" and "shutdown" commands from the Web GUI.

**Comment by canton7** [comment]
@lukehamburg https://github.com/syncthing/syncthing/tree/master/etc/macosx-launchd ?

**Comment by lukehamburg** [comment]
I know about that, but TBH for some reason those settings do not work very well.  As I wrote, I frequently wind up with 2 instances of syncthing running for some reason.

**Comment by calmh** [comment]
There can only be one, per config directory. Locking ensures this.

When STNORESTART is *not* set, you will see two syncthing processes. One manages the other. This is normal. It is still just one syncthing instance.

When STNORESTART *is* set, there is only one syncthing process, managed by something like launchd. (Those launchd settings work perfectly for me by the way :)

**Comment by lukehamburg** [comment]
Thanks for the reply.  Yes I understand that, however the behavior I am seeing is that under <some unpredictable cases> that LaunchD thinks that Syncthing is *not* running anymore even though it is and endlessly attempts to spawn a new instance, which floods the log and causes high CPU and battery drain.  The only way out that I have found is to 'sudo kill <pid_of_syncthing>'

**Comment by calmh** [comment]
That's odd indeed.

**Comment by lukehamburg** [comment]
Agreed.  Normally I would chalk it up to being a one-off type of issue but it has happened to me multiple times now on 2 different Macs (both running 10.12.1 and the latest syncthing). I am not sure what could cause it, are there any extra debug options I can enable to get more info on internals?

**Comment by calmh** [comment]
Lots of them, but none that relate to launching more than one instance - that sounds like you want to debug launchd instead. See https://docs.syncthing.net/dev/debugging.html and `syncthing -help`, and this is now a support discussion way unrelated to this issue, so lets take it to the forum for any continuation.

**Comment by imsodin** [comment]
Fixed by #278
